### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by BrianSHenderson** [jgdovin/meteor-html-pdf#1]
A very useful package.

Do you have any sample code for streaming a PDF document to the browser?

**Comment by jgdovin** [comment]
Hey @BrianSHenderson thanks for the feedback. I am planning to put out a sample application shortly, things got a little crazy with job interviews the last couple of days, but I am definitely going to put out some samples very soon and may be updating the package to pre-process the pdf's to be easier to handle client side.

**Comment by BrianSHenderson** [comment]
Should prove a very useful tool for many. Look forward to the sample code.

**Comment by jgdovin** [comment]
I have added a new method that easily handles pdf downloads automatically if you do not need to do any further processing.

```
Meteor.pdf.save('<h1>Some killer html goes here</h1>', 'someFileName');
```

thats all it takes, this includes the work around that I use with a collection to temporarily store the pdf data so that the data does not get muddled. I will continue to research a way to get the other methods working, but for now this is a very good use of the tool and makes it even easier to get started with the package :)

**Comment by BrianSHenderson** [comment]
Many thanks, exactly what I need.
